stages:
    - test

test:
    stage: test
    script:
        - echo "Testing"
        - apt-get update -qy
        - apt-get install -y python-dev python-pip
        - python -m unittest discover -t ./tests
