stages:
    - test

test:
    stage: test
    script:
        - echo "Testing"
        - apk update
        - apk add --update-cache python3 pip3
        - pip3 install pip AWSIoTPythonSDK==1.4.8
        - python3 -m unittest discover -s tests/
