stages:
    - test

test:
    stage: test
    script:
        - echo "Testing"
        - apk update
        - apk add --update-cache python python-dev py-pip
        - python -m unittest ./tests/test_device_software.py
