stages:
    - test

test:
    stage: test
    script:
        - echo "Testing"
        - apk update
        - apk add --update-cache python3=3.6
        - python -m unittest ./tests/test_device_software.py
