name: Switch
gpios:
  led:
    type: led
    state:
      'on': false
      color: red
  led2:
    type: led
    state:
      'on': false
      color: blue
  switch:
    type: switch
    state:
      open: true

