name: Humidity Sensor 1
gpios:
  humidity_sensor:
    type: sensor
    state:
      # the initial value
      value: -80
      
      # the minimal value
      min: 15
      
      # the maximum value
      max: 30
      
      # the step-size if the value goes up or down
      increment: 1
      
      # the unit (UI only, empty string for unitless)
      unit: "hPa"

