version: "3"
services:

  control_panel_emulator:
    image: csiot/emulator
    ports:
      - "127.0.0.1:5558:9292"
    volumes:
      - "./devices/control_panel/config.yaml:/emulator/config.yaml"

  control_panel_software:
    build:
      context: devices/control_panel
      dockerfile: ../../Dockerfile
    volumes:
      - "./devices/control_panel/:/usr/src/app/"
      - "./software_class/:/usr/src/app/software_class/"
    environment:
      HARDWARE_URL: http://control_panel_emulator:9292
      DEVICE_NAME: control_panel
      INTERVAL_TIME: 30
      AWS_IOT_ENDPOINT: ${AWS_ENDPOINT}
      PYTHONUNBUFFERED: 1

  soilmoisture1_emulator:
    image: csiot/emulator
    ports:
      - "127.0.0.1:5555:9292"
    volumes:
      - "./devices/soilMoisture1_sensor/config.yaml:/emulator/config.yaml"

  soilmoisture1_software:
    build:
      context: devices/soilMoisture1_sensor
      dockerfile: ../../Dockerfile
    volumes:
      - "./devices/soilMoisture1_sensor/:/usr/src/app/"
      - "./software_class/:/usr/src/app/software_class/"
    environment:
      HARDWARE_URL: http://soilmoisture1_emulator:9292
      DEVICE_NAME: soilMoisture1_sensor
      INTERVAL_TIME: 30
      AWS_IOT_ENDPOINT: ${AWS_ENDPOINT}
      PYTHONUNBUFFERED: 1

  soilmoisture2_emulator:
    image: csiot/emulator
    ports:
      - "127.0.0.1:5556:9292"
    volumes:
      - "./devices/soilMoisture2_sensor/config.yaml:/emulator/config.yaml"

  soilmoisture2_software:
    build:
      context: devices/soilMoisture2_sensor
      dockerfile: ../../Dockerfile
    volumes:
      - "./devices/soilMoisture2_sensor/:/usr/src/app/"
      - "./software_class/:/usr/src/app/software_class/"
    environment:
      HARDWARE_URL: http://soilmoisture2_emulator:9292
      DEVICE_NAME: soilMoisture2_sensor
      INTERVAL_TIME: 30
      AWS_IOT_ENDPOINT: ${AWS_ENDPOINT}
      PYTHONUNBUFFERED: 1

  rain_barrel_sensor_emulator:
    image: csiot/emulator    
    ports:
      - "127.0.0.1:5559:9292"
    volumes:
      - "./devices/rain_barrel_sensor/config.yaml:/emulator/config.yaml"

  rain_barrel_sensor_software:
    build:
      context: devices/rain_barrel_sensor
      dockerfile: ../../Dockerfile
    volumes:
       - "./devices/rain_barrel_sensor/:/usr/src/app/"
       - "./software_class/:/usr/src/app/software_class/"
    environment:
       HARDWARE_URL: http://rain_barrel_sensor_emulator:9292
       DEVICE_NAME: rain_barrel_sensor
       INTERVAL_TIME: 30
       AWS_IOT_ENDPOINT: ${AWS_ENDPOINT}
       PYTHONUNBUFFERED: 1

  valve_emulator:
    image: csiot/emulator
    ports:
      - "127.0.0.1:5557:9292"
    volumes:
      - "./devices/water_valve/config.yaml:/emulator/config.yaml"

  valve_software:
    build:
      context: devices/water_valve
      dockerfile: ../../Dockerfile
    depends_on:
      - valve_emulator
    volumes:
      - "./devices/water_valve/:/usr/src/app/"
      - "./software_class/:/usr/src/app/software_class/"
    environment:
      HARDWARE_URL: http://valve_emulator:9292
      DEVICE_NAME: water_valve
      AWS_IOT_ENDPOINT: ${AWS_ENDPOINT}
      PYTHONUNBUFFERED: 1
