name: soilMoisture3_sensor bed 2
gpios:

  soilMoistureSensor:
    type: sensor
    state:
      # the initial value
      value: 50
      
      # the minimal value
      min: 0
      
      # the maximum value
      max: 300
      
      # the step-size if the value goes up or down
      increment: 1
      
      # the unit (UI only, empty string for unitless)
      unit: "nFk (%)"
